package dev.vinpol.nebula.dragonship.automation.behaviour.state;

public enum FailureReason {
    NOT_IN_ORBIT,
    CARGO_IS_FULL, ACTIVE_COOLDOWN, DOCKED, IN_TRANSIT, NOT_DOCKED, ALREADY_AT_LOCATION, FAILURE, NO_WAYPOINTS_FOUND_IN_CURRENT_SYSTEM, NO_CARGO_TO_SELL, FUEL_IS_EMPTY, NOT_AT_MARKET_WAYPOINT, MARKET_DOES_NOT_SELL_FUEL, FUEL_IS_FULL
}
