nebula:
    st:
        token: ${NEBULA_TOKEN}
        url: https://api.spacetraders.io/v2/

nebula.ext.sync-on-boot: ${NEBULA_SYNC_ON_BOOT:false}

gg:
    jte:
        developmentMode: false
spring:
    groovy:
        template:
            check-template-location: false
    devtools:
        add-properties: false
    messages:
        use-code-as-default-message: true
