nebula:
    st:
        token: ${NEBULA_TOKEN}
        auto-register: false
        url: https://api.spacetraders.io/v2/
        ext:
           on-boot: ${NEBULA_ON_BOOT:true}

gg:
    jte:
        developmentMode: false
spring:
    groovy:
        template:
            check-template-location: false
    devtools:
        add-properties: false
    messages:
        use-code-as-default-message: true
