logging.level.dev.vinpol.nebula.dragonship: INFO
logging.level.dev.vinpol.nebula.dragonship.automation: INFO
logging.level.dev.vinpol.nebula.dragonship.bigbrain: DEBUG
logging.level.dev.vinpol.nebula.dragonship.automation.behaviour.navigation: DEBUG
logging.level.dev.vinpol.nebula.dragonship.web.support.vite: DEBUG

nebula:
    st:
        auto-register: true
        ext:
            on-boot: true


vite:
    baseUrl: http://localhost:5173/
    devPort: 5173

gg:
    jte:
        developmentMode: true
        templateLocation: src/main/frontend
        classLocation: target/jte-classes

management:
    endpoints:
        web:
            exposure:
                include: "mappings"
