logging.level.dev.vinpol.nebula.dragonship: INFO
logging.level.dev.vinpol.nebula.dragonship.automation: INFO
logging.level.dev.vinpol.nebula.dragonship.web.support.vite: DEBUG

nebula.ext.sync-on-boot: false

vite:
    baseUrl: http://localhost:5173/
    devPort: 5173

gg:
    jte:
        developmentMode: true
        templateLocation: src/main/jte
        classLocation: target/jte-classes

management:
    endpoints:
        web:
            exposure:
                include: "mappings"
