/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import java.io.IOException;

/**
 * Agent details.
 */

public class Agent {
  public static final String SERIALIZED_NAME_ACCOUNT_ID = "accountId";

  private String accountId;

  public static final String SERIALIZED_NAME_SYMBOL = "symbol";

  private String symbol;

  public static final String SERIALIZED_NAME_HEADQUARTERS = "headquarters";

  private String headquarters;

  public static final String SERIALIZED_NAME_CREDITS = "credits";

  private Long credits;

  public static final String SERIALIZED_NAME_STARTING_FACTION = "startingFaction";

  private String startingFaction;

  public static final String SERIALIZED_NAME_SHIP_COUNT = "shipCount";

  private Integer shipCount;

  public Agent() {
  }

  public Agent accountId(String accountId) {

    this.accountId = accountId;
    return this;
  }

   /**
   * Account ID that is tied to this agent. Only included on your own agent.
   * @return accountId
  **/
  

  public String getAccountId() {
    return accountId;
  }


  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  public Agent symbol(String symbol) {

    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol of the agent.
   * @return symbol
  **/


  public String getSymbol() {
    return symbol;
  }


  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public Agent headquarters(String headquarters) {

    this.headquarters = headquarters;
    return this;
  }

   /**
   * The headquarters of the agent.
   * @return headquarters
  **/


  public String getHeadquarters() {
    return headquarters;
  }


  public void setHeadquarters(String headquarters) {
    this.headquarters = headquarters;
  }


  public Agent credits(Long credits) {

    this.credits = credits;
    return this;
  }

   /**
   * The number of credits the agent has available. Credits can be negative if funds have been overdrawn.
   * @return credits
  **/


  public Long getCredits() {
    return credits;
  }


  public void setCredits(Long credits) {
    this.credits = credits;
  }


  public Agent startingFaction(String startingFaction) {

    this.startingFaction = startingFaction;
    return this;
  }

   /**
   * The faction the agent started with.
   * @return startingFaction
  **/


  public String getStartingFaction() {
    return startingFaction;
  }


  public void setStartingFaction(String startingFaction) {
    this.startingFaction = startingFaction;
  }


  public Agent shipCount(Integer shipCount) {

    this.shipCount = shipCount;
    return this;
  }

   /**
   * How many ships are owned by the agent.
   * @return shipCount
  **/


  public Integer getShipCount() {
    return shipCount;
  }


  public void setShipCount(Integer shipCount) {
    this.shipCount = shipCount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Agent agent = (Agent) o;
    return Objects.equals(this.accountId, agent.accountId) &&
        Objects.equals(this.symbol, agent.symbol) &&
        Objects.equals(this.headquarters, agent.headquarters) &&
        Objects.equals(this.credits, agent.credits) &&
        Objects.equals(this.startingFaction, agent.startingFaction) &&
        Objects.equals(this.shipCount, agent.shipCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, symbol, headquarters, credits, startingFaction, shipCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Agent {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    headquarters: ").append(toIndentedString(headquarters)).append("\n");
    sb.append("    credits: ").append(toIndentedString(credits)).append("\n");
    sb.append("    startingFaction: ").append(toIndentedString(startingFaction)).append("\n");
    sb.append("    shipCount: ").append(toIndentedString(shipCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

