/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.TradeSymbol;
import java.io.IOException;

/**
 * The details of the required construction materials for a given waypoint under construction.
 */

public class ConstructionMaterial {
  public static final String SERIALIZED_NAME_TRADE_SYMBOL = "tradeSymbol";
  
  private TradeSymbol tradeSymbol;

  public static final String SERIALIZED_NAME_REQUIRED = "required";
  
  private Integer required;

  public static final String SERIALIZED_NAME_FULFILLED = "fulfilled";
  
  private Integer fulfilled;

  public ConstructionMaterial() {
  }

  public ConstructionMaterial tradeSymbol(TradeSymbol tradeSymbol) {

    this.tradeSymbol = tradeSymbol;
    return this;
  }

   /**
   * Get tradeSymbol
   * @return tradeSymbol
  **/
  

  public TradeSymbol getTradeSymbol() {
    return tradeSymbol;
  }


  public void setTradeSymbol(TradeSymbol tradeSymbol) {
    this.tradeSymbol = tradeSymbol;
  }


  public ConstructionMaterial required(Integer required) {

    this.required = required;
    return this;
  }

   /**
   * The number of units required.
   * @return required
  **/
  

  public Integer getRequired() {
    return required;
  }


  public void setRequired(Integer required) {
    this.required = required;
  }


  public ConstructionMaterial fulfilled(Integer fulfilled) {

    this.fulfilled = fulfilled;
    return this;
  }

   /**
   * The number of units fulfilled toward the required amount.
   * @return fulfilled
  **/
  

  public Integer getFulfilled() {
    return fulfilled;
  }


  public void setFulfilled(Integer fulfilled) {
    this.fulfilled = fulfilled;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConstructionMaterial constructionMaterial = (ConstructionMaterial) o;
    return Objects.equals(this.tradeSymbol, constructionMaterial.tradeSymbol) &&
        Objects.equals(this.required, constructionMaterial.required) &&
        Objects.equals(this.fulfilled, constructionMaterial.fulfilled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradeSymbol, required, fulfilled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConstructionMaterial {\n");
    sb.append("    tradeSymbol: ").append(toIndentedString(tradeSymbol)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    fulfilled: ").append(toIndentedString(fulfilled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

