/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.Cooldown;
import dev.vinpol.spacetraders.sdk.models.Survey;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * CreateSurvey201ResponseData
 */

public class CreateSurvey201ResponseData {
  public static final String SERIALIZED_NAME_COOLDOWN = "cooldown";
  
  private Cooldown cooldown;

  public static final String SERIALIZED_NAME_SURVEYS = "surveys";
  
  private List<Survey> surveys = new ArrayList<>();

  public CreateSurvey201ResponseData() {
  }

  public CreateSurvey201ResponseData cooldown(Cooldown cooldown) {

    this.cooldown = cooldown;
    return this;
  }

   /**
   * Get cooldown
   * @return cooldown
  **/
  

  public Cooldown getCooldown() {
    return cooldown;
  }


  public void setCooldown(Cooldown cooldown) {
    this.cooldown = cooldown;
  }


  public CreateSurvey201ResponseData surveys(List<Survey> surveys) {

    this.surveys = surveys;
    return this;
  }

  public CreateSurvey201ResponseData addSurveysItem(Survey surveysItem) {
    if (this.surveys == null) {
      this.surveys = new ArrayList<>();
    }
    this.surveys.add(surveysItem);
    return this;
  }

   /**
   * Surveys created by this action.
   * @return surveys
  **/
  

  public List<Survey> getSurveys() {
    return surveys;
  }


  public void setSurveys(List<Survey> surveys) {
    this.surveys = surveys;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSurvey201ResponseData createSurvey201ResponseData = (CreateSurvey201ResponseData) o;
    return Objects.equals(this.cooldown, createSurvey201ResponseData.cooldown) &&
        Objects.equals(this.surveys, createSurvey201ResponseData.surveys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cooldown, surveys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSurvey201ResponseData {\n");
    sb.append("    cooldown: ").append(toIndentedString(cooldown)).append("\n");
    sb.append("    surveys: ").append(toIndentedString(surveys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

