/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.Cooldown;
import dev.vinpol.spacetraders.sdk.models.ScannedSystem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * CreateShipSystemScan201ResponseData
 */

public class CreateShipSystemScan201ResponseData {
  public static final String SERIALIZED_NAME_COOLDOWN = "cooldown";
  
  private Cooldown cooldown;

  public static final String SERIALIZED_NAME_SYSTEMS = "systems";
  
  private List<ScannedSystem> systems = new ArrayList<>();

  public CreateShipSystemScan201ResponseData() {
  }

  public CreateShipSystemScan201ResponseData cooldown(Cooldown cooldown) {

    this.cooldown = cooldown;
    return this;
  }

   /**
   * Get cooldown
   * @return cooldown
  **/
  

  public Cooldown getCooldown() {
    return cooldown;
  }


  public void setCooldown(Cooldown cooldown) {
    this.cooldown = cooldown;
  }


  public CreateShipSystemScan201ResponseData systems(List<ScannedSystem> systems) {

    this.systems = systems;
    return this;
  }

  public CreateShipSystemScan201ResponseData addSystemsItem(ScannedSystem systemsItem) {
    if (this.systems == null) {
      this.systems = new ArrayList<>();
    }
    this.systems.add(systemsItem);
    return this;
  }

   /**
   * List of scanned systems.
   * @return systems
  **/
  

  public List<ScannedSystem> getSystems() {
    return systems;
  }


  public void setSystems(List<ScannedSystem> systems) {
    this.systems = systems;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateShipSystemScan201ResponseData createShipSystemScan201ResponseData = (CreateShipSystemScan201ResponseData) o;
    return Objects.equals(this.cooldown, createShipSystemScan201ResponseData.cooldown) &&
        Objects.equals(this.systems, createShipSystemScan201ResponseData.systems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cooldown, systems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateShipSystemScan201ResponseData {\n");
    sb.append("    cooldown: ").append(toIndentedString(cooldown)).append("\n");
    sb.append("    systems: ").append(toIndentedString(systems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

