/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import java.io.IOException;

/**
 * DeliverContractRequest
 */

public class DeliverContractRequest {
  public static final String SERIALIZED_NAME_SHIP_SYMBOL = "shipSymbol";
  
  private String shipSymbol;

  public static final String SERIALIZED_NAME_TRADE_SYMBOL = "tradeSymbol";
  
  private String tradeSymbol;

  public static final String SERIALIZED_NAME_UNITS = "units";
  
  private Integer units;

  public DeliverContractRequest() {
  }

  public DeliverContractRequest shipSymbol(String shipSymbol) {

    this.shipSymbol = shipSymbol;
    return this;
  }

   /**
   * Symbol of a ship located in the destination to deliver a contract and that has a good to deliver in its cargo.
   * @return shipSymbol
  **/
  

  public String getShipSymbol() {
    return shipSymbol;
  }


  public void setShipSymbol(String shipSymbol) {
    this.shipSymbol = shipSymbol;
  }


  public DeliverContractRequest tradeSymbol(String tradeSymbol) {

    this.tradeSymbol = tradeSymbol;
    return this;
  }

   /**
   * The symbol of the good to deliver.
   * @return tradeSymbol
  **/
  

  public String getTradeSymbol() {
    return tradeSymbol;
  }


  public void setTradeSymbol(String tradeSymbol) {
    this.tradeSymbol = tradeSymbol;
  }


  public DeliverContractRequest units(Integer units) {

    this.units = units;
    return this;
  }

   /**
   * Amount of units to deliver.
   * @return units
  **/
  

  public Integer getUnits() {
    return units;
  }


  public void setUnits(Integer units) {
    this.units = units;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliverContractRequest deliverContractRequest = (DeliverContractRequest) o;
    return Objects.equals(this.shipSymbol, deliverContractRequest.shipSymbol) &&
        Objects.equals(this.tradeSymbol, deliverContractRequest.tradeSymbol) &&
        Objects.equals(this.units, deliverContractRequest.units);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipSymbol, tradeSymbol, units);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliverContractRequest {\n");
    sb.append("    shipSymbol: ").append(toIndentedString(shipSymbol)).append("\n");
    sb.append("    tradeSymbol: ").append(toIndentedString(tradeSymbol)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

