/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.ExtractionYield;
import java.io.IOException;

/**
 * Extraction details.
 */

public class Extraction {
  public static final String SERIALIZED_NAME_SHIP_SYMBOL = "shipSymbol";

  private String shipSymbol;

  public static final String SERIALIZED_NAME_YIELD = "yield";

  private ExtractionYield yield;

  public Extraction() {
  }

  public Extraction shipSymbol(String shipSymbol) {

    this.shipSymbol = shipSymbol;
    return this;
  }

   /**
   * Symbol of the ship that executed the extraction.
   * @return shipSymbol
  **/


  public String getShipSymbol() {
    return shipSymbol;
  }


  public void setShipSymbol(String shipSymbol) {
    this.shipSymbol = shipSymbol;
  }


  public Extraction yield(ExtractionYield yield) {

    this.yield = yield;
    return this;
  }

   /**
   * Get yield
   * @return yield
  **/


  public ExtractionYield getYield() {
    return yield;
  }


  public void setYield(ExtractionYield yield) {
    this.yield = yield;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Extraction extraction = (Extraction) o;
    return Objects.equals(this.shipSymbol, extraction.shipSymbol) &&
        Objects.equals(this.yield, extraction.yield);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipSymbol, yield);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Extraction {\n");
    sb.append("    shipSymbol: ").append(toIndentedString(shipSymbol)).append("\n");
    sb.append("    yield: ").append(toIndentedString(yield)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

