/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.GetStatus200ResponseAnnouncementsInner;
import dev.vinpol.spacetraders.sdk.models.GetStatus200ResponseLeaderboards;
import dev.vinpol.spacetraders.sdk.models.GetStatus200ResponseLinksInner;
import dev.vinpol.spacetraders.sdk.models.GetStatus200ResponseServerResets;
import dev.vinpol.spacetraders.sdk.models.GetStatus200ResponseStats;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * GetStatus200Response
 */

public class GetStatus200Response {
  public static final String SERIALIZED_NAME_STATUS = "status";

  private String status;

  public static final String SERIALIZED_NAME_VERSION = "version";

  private String version;

  public static final String SERIALIZED_NAME_RESET_DATE = "resetDate";

  private String resetDate;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";

  private String description;

  public static final String SERIALIZED_NAME_STATS = "stats";

  private GetStatus200ResponseStats stats;

  public static final String SERIALIZED_NAME_LEADERBOARDS = "leaderboards";

  private GetStatus200ResponseLeaderboards leaderboards;

  public static final String SERIALIZED_NAME_SERVER_RESETS = "serverResets";

  private GetStatus200ResponseServerResets serverResets;

  public static final String SERIALIZED_NAME_ANNOUNCEMENTS = "announcements";

  private List<GetStatus200ResponseAnnouncementsInner> announcements = new ArrayList<>();

  public static final String SERIALIZED_NAME_LINKS = "links";

  private List<GetStatus200ResponseLinksInner> links = new ArrayList<>();

  public GetStatus200Response() {
  }

  public GetStatus200Response status(String status) {

    this.status = status;
    return this;
  }

   /**
   * The current status of the game server.
   * @return status
  **/


  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public GetStatus200Response version(String version) {

    this.version = version;
    return this;
  }

   /**
   * The current version of the API.
   * @return version
  **/


  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public GetStatus200Response resetDate(String resetDate) {

    this.resetDate = resetDate;
    return this;
  }

   /**
   * The date when the game server was last reset.
   * @return resetDate
  **/


  public String getResetDate() {
    return resetDate;
  }


  public void setResetDate(String resetDate) {
    this.resetDate = resetDate;
  }


  public GetStatus200Response description(String description) {

    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/


  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public GetStatus200Response stats(GetStatus200ResponseStats stats) {

    this.stats = stats;
    return this;
  }

   /**
   * Get stats
   * @return stats
  **/


  public GetStatus200ResponseStats getStats() {
    return stats;
  }


  public void setStats(GetStatus200ResponseStats stats) {
    this.stats = stats;
  }


  public GetStatus200Response leaderboards(GetStatus200ResponseLeaderboards leaderboards) {

    this.leaderboards = leaderboards;
    return this;
  }

   /**
   * Get leaderboards
   * @return leaderboards
  **/


  public GetStatus200ResponseLeaderboards getLeaderboards() {
    return leaderboards;
  }


  public void setLeaderboards(GetStatus200ResponseLeaderboards leaderboards) {
    this.leaderboards = leaderboards;
  }


  public GetStatus200Response serverResets(GetStatus200ResponseServerResets serverResets) {

    this.serverResets = serverResets;
    return this;
  }

   /**
   * Get serverResets
   * @return serverResets
  **/


  public GetStatus200ResponseServerResets getServerResets() {
    return serverResets;
  }


  public void setServerResets(GetStatus200ResponseServerResets serverResets) {
    this.serverResets = serverResets;
  }


  public GetStatus200Response announcements(List<GetStatus200ResponseAnnouncementsInner> announcements) {

    this.announcements = announcements;
    return this;
  }

  public GetStatus200Response addAnnouncementsItem(GetStatus200ResponseAnnouncementsInner announcementsItem) {
    if (this.announcements == null) {
      this.announcements = new ArrayList<>();
    }
    this.announcements.add(announcementsItem);
    return this;
  }

   /**
   * Get announcements
   * @return announcements
  **/


  public List<GetStatus200ResponseAnnouncementsInner> getAnnouncements() {
    return announcements;
  }


  public void setAnnouncements(List<GetStatus200ResponseAnnouncementsInner> announcements) {
    this.announcements = announcements;
  }


  public GetStatus200Response links(List<GetStatus200ResponseLinksInner> links) {

    this.links = links;
    return this;
  }

  public GetStatus200Response addLinksItem(GetStatus200ResponseLinksInner linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/


  public List<GetStatus200ResponseLinksInner> getLinks() {
    return links;
  }


  public void setLinks(List<GetStatus200ResponseLinksInner> links) {
    this.links = links;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetStatus200Response getStatus200Response = (GetStatus200Response) o;
    return Objects.equals(this.status, getStatus200Response.status) &&
        Objects.equals(this.version, getStatus200Response.version) &&
        Objects.equals(this.resetDate, getStatus200Response.resetDate) &&
        Objects.equals(this.description, getStatus200Response.description) &&
        Objects.equals(this.stats, getStatus200Response.stats) &&
        Objects.equals(this.leaderboards, getStatus200Response.leaderboards) &&
        Objects.equals(this.serverResets, getStatus200Response.serverResets) &&
        Objects.equals(this.announcements, getStatus200Response.announcements) &&
        Objects.equals(this.links, getStatus200Response.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, version, resetDate, description, stats, leaderboards, serverResets, announcements, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetStatus200Response {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    resetDate: ").append(toIndentedString(resetDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("    leaderboards: ").append(toIndentedString(leaderboards)).append("\n");
    sb.append("    serverResets: ").append(toIndentedString(serverResets)).append("\n");
    sb.append("    announcements: ").append(toIndentedString(announcements)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

