/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import java.io.IOException;

/**
 * GetStatus200ResponseServerResets
 */

public class GetStatus200ResponseServerResets {
  public static final String SERIALIZED_NAME_NEXT = "next";
  
  private String next;

  public static final String SERIALIZED_NAME_FREQUENCY = "frequency";
  
  private String frequency;

  public GetStatus200ResponseServerResets() {
  }

  public GetStatus200ResponseServerResets next(String next) {

    this.next = next;
    return this;
  }

   /**
   * The date and time when the game server will reset.
   * @return next
  **/
  

  public String getNext() {
    return next;
  }


  public void setNext(String next) {
    this.next = next;
  }


  public GetStatus200ResponseServerResets frequency(String frequency) {

    this.frequency = frequency;
    return this;
  }

   /**
   * How often we intend to reset the game server.
   * @return frequency
  **/
  

  public String getFrequency() {
    return frequency;
  }


  public void setFrequency(String frequency) {
    this.frequency = frequency;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetStatus200ResponseServerResets getStatus200ResponseServerResets = (GetStatus200ResponseServerResets) o;
    return Objects.equals(this.next, getStatus200ResponseServerResets.next) &&
        Objects.equals(this.frequency, getStatus200ResponseServerResets.frequency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(next, frequency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetStatus200ResponseServerResets {\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

