/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.Agent;
import dev.vinpol.spacetraders.sdk.models.Cooldown;
import dev.vinpol.spacetraders.sdk.models.MarketTransaction;
import dev.vinpol.spacetraders.sdk.models.ShipNav;
import java.io.IOException;

/**
 * JumpShip200ResponseData
 */

public class JumpShip200ResponseData {
  public static final String SERIALIZED_NAME_NAV = "nav";
  
  private ShipNav nav;

  public static final String SERIALIZED_NAME_COOLDOWN = "cooldown";
  
  private Cooldown cooldown;

  public static final String SERIALIZED_NAME_TRANSACTION = "transaction";
  
  private MarketTransaction transaction;

  public static final String SERIALIZED_NAME_AGENT = "agent";
  
  private Agent agent;

  public JumpShip200ResponseData() {
  }

  public JumpShip200ResponseData nav(ShipNav nav) {

    this.nav = nav;
    return this;
  }

   /**
   * Get nav
   * @return nav
  **/
  

  public ShipNav getNav() {
    return nav;
  }


  public void setNav(ShipNav nav) {
    this.nav = nav;
  }


  public JumpShip200ResponseData cooldown(Cooldown cooldown) {

    this.cooldown = cooldown;
    return this;
  }

   /**
   * Get cooldown
   * @return cooldown
  **/
  

  public Cooldown getCooldown() {
    return cooldown;
  }


  public void setCooldown(Cooldown cooldown) {
    this.cooldown = cooldown;
  }


  public JumpShip200ResponseData transaction(MarketTransaction transaction) {

    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  

  public MarketTransaction getTransaction() {
    return transaction;
  }


  public void setTransaction(MarketTransaction transaction) {
    this.transaction = transaction;
  }


  public JumpShip200ResponseData agent(Agent agent) {

    this.agent = agent;
    return this;
  }

   /**
   * Get agent
   * @return agent
  **/
  

  public Agent getAgent() {
    return agent;
  }


  public void setAgent(Agent agent) {
    this.agent = agent;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JumpShip200ResponseData jumpShip200ResponseData = (JumpShip200ResponseData) o;
    return Objects.equals(this.nav, jumpShip200ResponseData.nav) &&
        Objects.equals(this.cooldown, jumpShip200ResponseData.cooldown) &&
        Objects.equals(this.transaction, jumpShip200ResponseData.transaction) &&
        Objects.equals(this.agent, jumpShip200ResponseData.agent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nav, cooldown, transaction, agent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JumpShip200ResponseData {\n");
    sb.append("    nav: ").append(toIndentedString(nav)).append("\n");
    sb.append("    cooldown: ").append(toIndentedString(cooldown)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

