/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.Agent;
import dev.vinpol.spacetraders.sdk.models.Ship;
import dev.vinpol.spacetraders.sdk.models.ShipyardTransaction;
import java.io.IOException;

/**
 * PurchaseShip201ResponseData
 */

public class PurchaseShip201ResponseData {
  public static final String SERIALIZED_NAME_AGENT = "agent";
  
  private Agent agent;

  public static final String SERIALIZED_NAME_SHIP = "ship";
  
  private Ship ship;

  public static final String SERIALIZED_NAME_TRANSACTION = "transaction";
  
  private ShipyardTransaction transaction;

  public PurchaseShip201ResponseData() {
  }

  public PurchaseShip201ResponseData agent(Agent agent) {

    this.agent = agent;
    return this;
  }

   /**
   * Get agent
   * @return agent
  **/
  

  public Agent getAgent() {
    return agent;
  }


  public void setAgent(Agent agent) {
    this.agent = agent;
  }


  public PurchaseShip201ResponseData ship(Ship ship) {

    this.ship = ship;
    return this;
  }

   /**
   * Get ship
   * @return ship
  **/
  

  public Ship getShip() {
    return ship;
  }


  public void setShip(Ship ship) {
    this.ship = ship;
  }


  public PurchaseShip201ResponseData transaction(ShipyardTransaction transaction) {

    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  

  public ShipyardTransaction getTransaction() {
    return transaction;
  }


  public void setTransaction(ShipyardTransaction transaction) {
    this.transaction = transaction;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseShip201ResponseData purchaseShip201ResponseData = (PurchaseShip201ResponseData) o;
    return Objects.equals(this.agent, purchaseShip201ResponseData.agent) &&
        Objects.equals(this.ship, purchaseShip201ResponseData.ship) &&
        Objects.equals(this.transaction, purchaseShip201ResponseData.transaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agent, ship, transaction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseShip201ResponseData {\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    ship: ").append(toIndentedString(ship)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

