/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * Result of a transaction for a ship modification, such as installing a mount or a module.
 */

public class ShipModificationTransaction {
  public static final String SERIALIZED_NAME_WAYPOINT_SYMBOL = "waypointSymbol";
  
  private String waypointSymbol;

  public static final String SERIALIZED_NAME_SHIP_SYMBOL = "shipSymbol";
  
  private String shipSymbol;

  public static final String SERIALIZED_NAME_TRADE_SYMBOL = "tradeSymbol";
  
  private String tradeSymbol;

  public static final String SERIALIZED_NAME_TOTAL_PRICE = "totalPrice";
  
  private Integer totalPrice;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  
  private OffsetDateTime timestamp;

  public ShipModificationTransaction() {
  }

  public ShipModificationTransaction waypointSymbol(String waypointSymbol) {

    this.waypointSymbol = waypointSymbol;
    return this;
  }

   /**
   * The symbol of the waypoint where the transaction took place.
   * @return waypointSymbol
  **/
  

  public String getWaypointSymbol() {
    return waypointSymbol;
  }


  public void setWaypointSymbol(String waypointSymbol) {
    this.waypointSymbol = waypointSymbol;
  }


  public ShipModificationTransaction shipSymbol(String shipSymbol) {

    this.shipSymbol = shipSymbol;
    return this;
  }

   /**
   * The symbol of the ship that made the transaction.
   * @return shipSymbol
  **/
  

  public String getShipSymbol() {
    return shipSymbol;
  }


  public void setShipSymbol(String shipSymbol) {
    this.shipSymbol = shipSymbol;
  }


  public ShipModificationTransaction tradeSymbol(String tradeSymbol) {

    this.tradeSymbol = tradeSymbol;
    return this;
  }

   /**
   * The symbol of the trade good.
   * @return tradeSymbol
  **/
  

  public String getTradeSymbol() {
    return tradeSymbol;
  }


  public void setTradeSymbol(String tradeSymbol) {
    this.tradeSymbol = tradeSymbol;
  }


  public ShipModificationTransaction totalPrice(Integer totalPrice) {

    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * The total price of the transaction.
   * minimum: 0
   * @return totalPrice
  **/
  

  public Integer getTotalPrice() {
    return totalPrice;
  }


  public void setTotalPrice(Integer totalPrice) {
    this.totalPrice = totalPrice;
  }


  public ShipModificationTransaction timestamp(OffsetDateTime timestamp) {

    this.timestamp = timestamp;
    return this;
  }

   /**
   * The timestamp of the transaction.
   * @return timestamp
  **/
  

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipModificationTransaction shipModificationTransaction = (ShipModificationTransaction) o;
    return Objects.equals(this.waypointSymbol, shipModificationTransaction.waypointSymbol) &&
        Objects.equals(this.shipSymbol, shipModificationTransaction.shipSymbol) &&
        Objects.equals(this.tradeSymbol, shipModificationTransaction.tradeSymbol) &&
        Objects.equals(this.totalPrice, shipModificationTransaction.totalPrice) &&
        Objects.equals(this.timestamp, shipModificationTransaction.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(waypointSymbol, shipSymbol, tradeSymbol, totalPrice, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipModificationTransaction {\n");
    sb.append("    waypointSymbol: ").append(toIndentedString(waypointSymbol)).append("\n");
    sb.append("    shipSymbol: ").append(toIndentedString(shipSymbol)).append("\n");
    sb.append("    tradeSymbol: ").append(toIndentedString(tradeSymbol)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

