/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.WaypointType;
import java.io.IOException;

/**
 * The destination or departure of a ships nav route.
 */

public class ShipNavRouteWaypoint {
  public static final String SERIALIZED_NAME_SYMBOL = "symbol";

  private String symbol;

  public static final String SERIALIZED_NAME_TYPE = "type";
  
  private WaypointType type;

  public static final String SERIALIZED_NAME_SYSTEM_SYMBOL = "systemSymbol";
  
  private String systemSymbol;

  public static final String SERIALIZED_NAME_X = "x";
  
  private Integer x;

  public static final String SERIALIZED_NAME_Y = "y";
  
  private Integer y;

  public ShipNavRouteWaypoint() {
  }

  public ShipNavRouteWaypoint symbol(String symbol) {

    this.symbol = symbol;
    return this;
  }

   /**
   * The symbol of the waypoint.
   * @return symbol
  **/
  

  public String getSymbol() {
    return symbol;
  }


  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public ShipNavRouteWaypoint type(WaypointType type) {

    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  

  public WaypointType getType() {
    return type;
  }


  public void setType(WaypointType type) {
    this.type = type;
  }


  public ShipNavRouteWaypoint systemSymbol(String systemSymbol) {

    this.systemSymbol = systemSymbol;
    return this;
  }

   /**
   * The symbol of the system.
   * @return systemSymbol
  **/
  

  public String getSystemSymbol() {
    return systemSymbol;
  }


  public void setSystemSymbol(String systemSymbol) {
    this.systemSymbol = systemSymbol;
  }


  public ShipNavRouteWaypoint x(Integer x) {

    this.x = x;
    return this;
  }

   /**
   * Position in the universe in the x axis.
   * @return x
  **/
  

  public Integer getX() {
    return x;
  }


  public void setX(Integer x) {
    this.x = x;
  }


  public ShipNavRouteWaypoint y(Integer y) {

    this.y = y;
    return this;
  }

   /**
   * Position in the universe in the y axis.
   * @return y
  **/
  

  public Integer getY() {
    return y;
  }


  public void setY(Integer y) {
    this.y = y;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipNavRouteWaypoint shipNavRouteWaypoint = (ShipNavRouteWaypoint) o;
    return Objects.equals(this.symbol, shipNavRouteWaypoint.symbol) &&
        Objects.equals(this.type, shipNavRouteWaypoint.type) &&
        Objects.equals(this.systemSymbol, shipNavRouteWaypoint.systemSymbol) &&
        Objects.equals(this.x, shipNavRouteWaypoint.x) &&
        Objects.equals(this.y, shipNavRouteWaypoint.y);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, type, systemSymbol, x, y);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipNavRouteWaypoint {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    systemSymbol: ").append(toIndentedString(systemSymbol)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

