/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import com.fasterxml.jackson.annotation.JsonValue;
import dev.vinpol.spacetraders.sdk.models.ShipRequirements;
import java.io.IOException;

/**
 * A module can be installed in a ship and provides a set of capabilities such as storage space or quarters for crew. Module installations are permanent.
 */

public class ShipModule {
  /**
   * The symbol of the module.
   */

  public enum SymbolEnum {
    MINERAL_PROCESSOR_I("MODULE_MINERAL_PROCESSOR_I"),

    GAS_PROCESSOR_I("MODULE_GAS_PROCESSOR_I"),

    CARGO_HOLD_I("MODULE_CARGO_HOLD_I"),

    CARGO_HOLD_II("MODULE_CARGO_HOLD_II"),

    CARGO_HOLD_III("MODULE_CARGO_HOLD_III"),

    CREW_QUARTERS_I("MODULE_CREW_QUARTERS_I"),

    ENVOY_QUARTERS_I("MODULE_ENVOY_QUARTERS_I"),

    PASSENGER_CABIN_I("MODULE_PASSENGER_CABIN_I"),

    MICRO_REFINERY_I("MODULE_MICRO_REFINERY_I"),

    ORE_REFINERY_I("MODULE_ORE_REFINERY_I"),

    FUEL_REFINERY_I("MODULE_FUEL_REFINERY_I"),

    SCIENCE_LAB_I("MODULE_SCIENCE_LAB_I"),

    JUMP_DRIVE_I("MODULE_JUMP_DRIVE_I"),

    JUMP_DRIVE_II("MODULE_JUMP_DRIVE_II"),

    JUMP_DRIVE_III("MODULE_JUMP_DRIVE_III"),

    WARP_DRIVE_I("MODULE_WARP_DRIVE_I"),

    WARP_DRIVE_II("MODULE_WARP_DRIVE_II"),

    WARP_DRIVE_III("MODULE_WARP_DRIVE_III"),

    SHIELD_GENERATOR_I("MODULE_SHIELD_GENERATOR_I"),

    SHIELD_GENERATOR_II("MODULE_SHIELD_GENERATOR_II");

    private String value;

    SymbolEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SymbolEnum fromValue(String value) {
      for (SymbolEnum b : SymbolEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String SERIALIZED_NAME_SYMBOL = "symbol";

  private SymbolEnum symbol;

  public static final String SERIALIZED_NAME_CAPACITY = "capacity";

  private Integer capacity;

  public static final String SERIALIZED_NAME_RANGE = "range";

  private Integer range;

  public static final String SERIALIZED_NAME_NAME = "name";

  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";

  private String description;

  public static final String SERIALIZED_NAME_REQUIREMENTS = "requirements";

  private ShipRequirements requirements;

  public ShipModule() {
  }

  public ShipModule symbol(SymbolEnum symbol) {

    this.symbol = symbol;
    return this;
  }

   /**
   * The symbol of the module.
   * @return symbol
  **/


  public SymbolEnum getSymbol() {
    return symbol;
  }


  public void setSymbol(SymbolEnum symbol) {
    this.symbol = symbol;
  }


  public ShipModule capacity(Integer capacity) {

    this.capacity = capacity;
    return this;
  }

   /**
   * Modules that provide capacity, such as cargo hold or crew quarters will show this value to denote how much of a bonus the module grants.
   * minimum: 0
   * @return capacity
  **/


  public Integer getCapacity() {
    return capacity;
  }


  public void setCapacity(Integer capacity) {
    this.capacity = capacity;
  }


  public ShipModule range(Integer range) {

    this.range = range;
    return this;
  }

   /**
   * Modules that have a range will such as a sensor array show this value to denote how far can the module reach with its capabilities.
   * minimum: 0
   * @return range
  **/


  public Integer getRange() {
    return range;
  }


  public void setRange(Integer range) {
    this.range = range;
  }


  public ShipModule name(String name) {

    this.name = name;
    return this;
  }

   /**
   * Name of this module.
   * @return name
  **/


  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ShipModule description(String description) {

    this.description = description;
    return this;
  }

   /**
   * Description of this module.
   * @return description
  **/


  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ShipModule requirements(ShipRequirements requirements) {

    this.requirements = requirements;
    return this;
  }

   /**
   * Get requirements
   * @return requirements
  **/


  public ShipRequirements getRequirements() {
    return requirements;
  }


  public void setRequirements(ShipRequirements requirements) {
    this.requirements = requirements;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipModule shipModule = (ShipModule) o;
    return Objects.equals(this.symbol, shipModule.symbol) &&
        Objects.equals(this.capacity, shipModule.capacity) &&
        Objects.equals(this.range, shipModule.range) &&
        Objects.equals(this.name, shipModule.name) &&
        Objects.equals(this.description, shipModule.description) &&
        Objects.equals(this.requirements, shipModule.requirements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, capacity, range, name, description, requirements);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipModule {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    range: ").append(toIndentedString(range)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

