/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.ActivityLevel;
import dev.vinpol.spacetraders.sdk.models.ShipEngine;
import dev.vinpol.spacetraders.sdk.models.ShipFrame;
import dev.vinpol.spacetraders.sdk.models.ShipModule;
import dev.vinpol.spacetraders.sdk.models.ShipMount;
import dev.vinpol.spacetraders.sdk.models.ShipReactor;
import dev.vinpol.spacetraders.sdk.models.ShipType;
import dev.vinpol.spacetraders.sdk.models.ShipyardShipCrew;
import dev.vinpol.spacetraders.sdk.models.SupplyLevel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 */

public class ShipyardShip {
  public static final String SERIALIZED_NAME_TYPE = "type";

  private ShipType type;

  public static final String SERIALIZED_NAME_NAME = "name";

  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";

  private String description;

  public static final String SERIALIZED_NAME_SUPPLY = "supply";

  private SupplyLevel supply;

  public static final String SERIALIZED_NAME_ACTIVITY = "activity";

  private ActivityLevel activity;

  public static final String SERIALIZED_NAME_PURCHASE_PRICE = "purchasePrice";

  private Integer purchasePrice;

  public static final String SERIALIZED_NAME_FRAME = "frame";

  private ShipFrame frame;

  public static final String SERIALIZED_NAME_REACTOR = "reactor";

  private ShipReactor reactor;

  public static final String SERIALIZED_NAME_ENGINE = "engine";

  private ShipEngine engine;

  public static final String SERIALIZED_NAME_MODULES = "modules";

  private List<ShipModule> modules = new ArrayList<>();

  public static final String SERIALIZED_NAME_MOUNTS = "mounts";

  private List<ShipMount> mounts = new ArrayList<>();

  public static final String SERIALIZED_NAME_CREW = "crew";

  private ShipyardShipCrew crew;

  public ShipyardShip() {
  }

  public ShipyardShip type(ShipType type) {

    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/


  public ShipType getType() {
    return type;
  }


  public void setType(ShipType type) {
    this.type = type;
  }


  public ShipyardShip name(String name) {

    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/


  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ShipyardShip description(String description) {

    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/


  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ShipyardShip supply(SupplyLevel supply) {

    this.supply = supply;
    return this;
  }

   /**
   * Get supply
   * @return supply
  **/


  public SupplyLevel getSupply() {
    return supply;
  }


  public void setSupply(SupplyLevel supply) {
    this.supply = supply;
  }


  public ShipyardShip activity(ActivityLevel activity) {

    this.activity = activity;
    return this;
  }

   /**
   * Get activity
   * @return activity
  **/
  

  public ActivityLevel getActivity() {
    return activity;
  }


  public void setActivity(ActivityLevel activity) {
    this.activity = activity;
  }


  public ShipyardShip purchasePrice(Integer purchasePrice) {

    this.purchasePrice = purchasePrice;
    return this;
  }

   /**
   * Get purchasePrice
   * @return purchasePrice
  **/


  public Integer getPurchasePrice() {
    return purchasePrice;
  }


  public void setPurchasePrice(Integer purchasePrice) {
    this.purchasePrice = purchasePrice;
  }


  public ShipyardShip frame(ShipFrame frame) {

    this.frame = frame;
    return this;
  }

   /**
   * Get frame
   * @return frame
  **/


  public ShipFrame getFrame() {
    return frame;
  }


  public void setFrame(ShipFrame frame) {
    this.frame = frame;
  }


  public ShipyardShip reactor(ShipReactor reactor) {

    this.reactor = reactor;
    return this;
  }

   /**
   * Get reactor
   * @return reactor
  **/


  public ShipReactor getReactor() {
    return reactor;
  }


  public void setReactor(ShipReactor reactor) {
    this.reactor = reactor;
  }


  public ShipyardShip engine(ShipEngine engine) {

    this.engine = engine;
    return this;
  }

   /**
   * Get engine
   * @return engine
  **/


  public ShipEngine getEngine() {
    return engine;
  }


  public void setEngine(ShipEngine engine) {
    this.engine = engine;
  }


  public ShipyardShip modules(List<ShipModule> modules) {

    this.modules = modules;
    return this;
  }

  public ShipyardShip addModulesItem(ShipModule modulesItem) {
    if (this.modules == null) {
      this.modules = new ArrayList<>();
    }
    this.modules.add(modulesItem);
    return this;
  }

   /**
   * Get modules
   * @return modules
  **/


  public List<ShipModule> getModules() {
    return modules;
  }


  public void setModules(List<ShipModule> modules) {
    this.modules = modules;
  }


  public ShipyardShip mounts(List<ShipMount> mounts) {

    this.mounts = mounts;
    return this;
  }

  public ShipyardShip addMountsItem(ShipMount mountsItem) {
    if (this.mounts == null) {
      this.mounts = new ArrayList<>();
    }
    this.mounts.add(mountsItem);
    return this;
  }

   /**
   * Get mounts
   * @return mounts
  **/


  public List<ShipMount> getMounts() {
    return mounts;
  }


  public void setMounts(List<ShipMount> mounts) {
    this.mounts = mounts;
  }


  public ShipyardShip crew(ShipyardShipCrew crew) {

    this.crew = crew;
    return this;
  }

   /**
   * Get crew
   * @return crew
  **/


  public ShipyardShipCrew getCrew() {
    return crew;
  }


  public void setCrew(ShipyardShipCrew crew) {
    this.crew = crew;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipyardShip shipyardShip = (ShipyardShip) o;
    return Objects.equals(this.type, shipyardShip.type) &&
        Objects.equals(this.name, shipyardShip.name) &&
        Objects.equals(this.description, shipyardShip.description) &&
        Objects.equals(this.supply, shipyardShip.supply) &&
        Objects.equals(this.activity, shipyardShip.activity) &&
        Objects.equals(this.purchasePrice, shipyardShip.purchasePrice) &&
        Objects.equals(this.frame, shipyardShip.frame) &&
        Objects.equals(this.reactor, shipyardShip.reactor) &&
        Objects.equals(this.engine, shipyardShip.engine) &&
        Objects.equals(this.modules, shipyardShip.modules) &&
        Objects.equals(this.mounts, shipyardShip.mounts) &&
        Objects.equals(this.crew, shipyardShip.crew);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, name, description, supply, activity, purchasePrice, frame, reactor, engine, modules, mounts, crew);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipyardShip {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    supply: ").append(toIndentedString(supply)).append("\n");
    sb.append("    activity: ").append(toIndentedString(activity)).append("\n");
    sb.append("    purchasePrice: ").append(toIndentedString(purchasePrice)).append("\n");
    sb.append("    frame: ").append(toIndentedString(frame)).append("\n");
    sb.append("    reactor: ").append(toIndentedString(reactor)).append("\n");
    sb.append("    engine: ").append(toIndentedString(engine)).append("\n");
    sb.append("    modules: ").append(toIndentedString(modules)).append("\n");
    sb.append("    mounts: ").append(toIndentedString(mounts)).append("\n");
    sb.append("    crew: ").append(toIndentedString(crew)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

