/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.TradeSymbol;
import java.io.IOException;

/**
 * The type of cargo item and the number of units.
 */

public class ShipCargoItem {
  public static final String SERIALIZED_NAME_SYMBOL = "symbol";

  private TradeSymbol symbol;

  public static final String SERIALIZED_NAME_NAME = "name";

  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";

  private String description;

  public static final String SERIALIZED_NAME_UNITS = "units";
  
  private Integer units;

  public ShipCargoItem() {
  }

  public ShipCargoItem symbol(TradeSymbol symbol) {

    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  

  public TradeSymbol getSymbol() {
    return symbol;
  }


  public void setSymbol(TradeSymbol symbol) {
    this.symbol = symbol;
  }


  public ShipCargoItem name(String name) {

    this.name = name;
    return this;
  }

   /**
   * The name of the cargo item type.
   * @return name
  **/
  

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ShipCargoItem description(String description) {

    this.description = description;
    return this;
  }

   /**
   * The description of the cargo item type.
   * @return description
  **/
  

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ShipCargoItem units(Integer units) {

    this.units = units;
    return this;
  }

   /**
   * The number of units of the cargo item.
   * minimum: 1
   * @return units
  **/
  

  public Integer getUnits() {
    return units;
  }


  public void setUnits(Integer units) {
    this.units = units;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipCargoItem shipCargoItem = (ShipCargoItem) o;
    return Objects.equals(this.symbol, shipCargoItem.symbol) &&
        Objects.equals(this.name, shipCargoItem.name) &&
        Objects.equals(this.description, shipCargoItem.description) &&
        Objects.equals(this.units, shipCargoItem.units);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, name, description, units);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipCargoItem {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

