/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.Cooldown;
import dev.vinpol.spacetraders.sdk.models.ShipCargo;
import dev.vinpol.spacetraders.sdk.models.ShipRefine201ResponseDataProducedInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * ShipRefine201ResponseData
 */

public class ShipRefine201ResponseData {
  public static final String SERIALIZED_NAME_CARGO = "cargo";

  private ShipCargo cargo;

  public static final String SERIALIZED_NAME_COOLDOWN = "cooldown";

  private Cooldown cooldown;

  public static final String SERIALIZED_NAME_PRODUCED = "produced";

  private List<ShipRefine201ResponseDataProducedInner> produced = new ArrayList<>();

  public static final String SERIALIZED_NAME_CONSUMED = "consumed";

  private List<ShipRefine201ResponseDataProducedInner> consumed = new ArrayList<>();

  public ShipRefine201ResponseData() {
  }

  public ShipRefine201ResponseData cargo(ShipCargo cargo) {

    this.cargo = cargo;
    return this;
  }

   /**
   * Get cargo
   * @return cargo
  **/


  public ShipCargo getCargo() {
    return cargo;
  }


  public void setCargo(ShipCargo cargo) {
    this.cargo = cargo;
  }


  public ShipRefine201ResponseData cooldown(Cooldown cooldown) {

    this.cooldown = cooldown;
    return this;
  }

   /**
   * Get cooldown
   * @return cooldown
  **/


  public Cooldown getCooldown() {
    return cooldown;
  }


  public void setCooldown(Cooldown cooldown) {
    this.cooldown = cooldown;
  }


  public ShipRefine201ResponseData produced(List<ShipRefine201ResponseDataProducedInner> produced) {

    this.produced = produced;
    return this;
  }

  public ShipRefine201ResponseData addProducedItem(ShipRefine201ResponseDataProducedInner producedItem) {
    if (this.produced == null) {
      this.produced = new ArrayList<>();
    }
    this.produced.add(producedItem);
    return this;
  }

   /**
   * Goods that were produced by this refining process.
   * @return produced
  **/


  public List<ShipRefine201ResponseDataProducedInner> getProduced() {
    return produced;
  }


  public void setProduced(List<ShipRefine201ResponseDataProducedInner> produced) {
    this.produced = produced;
  }


  public ShipRefine201ResponseData consumed(List<ShipRefine201ResponseDataProducedInner> consumed) {

    this.consumed = consumed;
    return this;
  }

  public ShipRefine201ResponseData addConsumedItem(ShipRefine201ResponseDataProducedInner consumedItem) {
    if (this.consumed == null) {
      this.consumed = new ArrayList<>();
    }
    this.consumed.add(consumedItem);
    return this;
  }

   /**
   * Goods that were consumed during this refining process.
   * @return consumed
  **/


  public List<ShipRefine201ResponseDataProducedInner> getConsumed() {
    return consumed;
  }


  public void setConsumed(List<ShipRefine201ResponseDataProducedInner> consumed) {
    this.consumed = consumed;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipRefine201ResponseData shipRefine201ResponseData = (ShipRefine201ResponseData) o;
    return Objects.equals(this.cargo, shipRefine201ResponseData.cargo) &&
        Objects.equals(this.cooldown, shipRefine201ResponseData.cooldown) &&
        Objects.equals(this.produced, shipRefine201ResponseData.produced) &&
        Objects.equals(this.consumed, shipRefine201ResponseData.consumed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cargo, cooldown, produced, consumed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipRefine201ResponseData {\n");
    sb.append("    cargo: ").append(toIndentedString(cargo)).append("\n");
    sb.append("    cooldown: ").append(toIndentedString(cooldown)).append("\n");
    sb.append("    produced: ").append(toIndentedString(produced)).append("\n");
    sb.append("    consumed: ").append(toIndentedString(consumed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

