/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import java.io.IOException;

/**
 * ShipyardShipCrew
 */

public class ShipyardShipCrew {
  public static final String SERIALIZED_NAME_REQUIRED = "required";
  
  private Integer required;

  public static final String SERIALIZED_NAME_CAPACITY = "capacity";
  
  private Integer capacity;

  public ShipyardShipCrew() {
  }

  public ShipyardShipCrew required(Integer required) {

    this.required = required;
    return this;
  }

   /**
   * Get required
   * @return required
  **/
  

  public Integer getRequired() {
    return required;
  }


  public void setRequired(Integer required) {
    this.required = required;
  }


  public ShipyardShipCrew capacity(Integer capacity) {

    this.capacity = capacity;
    return this;
  }

   /**
   * Get capacity
   * @return capacity
  **/
  

  public Integer getCapacity() {
    return capacity;
  }


  public void setCapacity(Integer capacity) {
    this.capacity = capacity;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipyardShipCrew shipyardShipCrew = (ShipyardShipCrew) o;
    return Objects.equals(this.required, shipyardShipCrew.required) &&
        Objects.equals(this.capacity, shipyardShipCrew.capacity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(required, capacity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipyardShipCrew {\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

