/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.Cooldown;
import dev.vinpol.spacetraders.sdk.models.ShipCargo;
import dev.vinpol.spacetraders.sdk.models.Siphon;
import java.io.IOException;

/**
 * SiphonResources201ResponseData
 */

public class SiphonResources201ResponseData {
  public static final String SERIALIZED_NAME_COOLDOWN = "cooldown";

  private Cooldown cooldown;

  public static final String SERIALIZED_NAME_SIPHON = "siphon";

  private Siphon siphon;

  public static final String SERIALIZED_NAME_CARGO = "cargo";

  private ShipCargo cargo;

  public SiphonResources201ResponseData() {
  }

  public SiphonResources201ResponseData cooldown(Cooldown cooldown) {

    this.cooldown = cooldown;
    return this;
  }

   /**
   * Get cooldown
   * @return cooldown
  **/


  public Cooldown getCooldown() {
    return cooldown;
  }


  public void setCooldown(Cooldown cooldown) {
    this.cooldown = cooldown;
  }


  public SiphonResources201ResponseData siphon(Siphon siphon) {

    this.siphon = siphon;
    return this;
  }

   /**
   * Get siphon
   * @return siphon
  **/


  public Siphon getSiphon() {
    return siphon;
  }


  public void setSiphon(Siphon siphon) {
    this.siphon = siphon;
  }


  public SiphonResources201ResponseData cargo(ShipCargo cargo) {

    this.cargo = cargo;
    return this;
  }

   /**
   * Get cargo
   * @return cargo
  **/


  public ShipCargo getCargo() {
    return cargo;
  }


  public void setCargo(ShipCargo cargo) {
    this.cargo = cargo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SiphonResources201ResponseData siphonResources201ResponseData = (SiphonResources201ResponseData) o;
    return Objects.equals(this.cooldown, siphonResources201ResponseData.cooldown) &&
        Objects.equals(this.siphon, siphonResources201ResponseData.siphon) &&
        Objects.equals(this.cargo, siphonResources201ResponseData.cargo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cooldown, siphon, cargo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SiphonResources201ResponseData {\n");
    sb.append("    cooldown: ").append(toIndentedString(cooldown)).append("\n");
    sb.append("    siphon: ").append(toIndentedString(siphon)).append("\n");
    sb.append("    cargo: ").append(toIndentedString(cargo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

