/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.Construction;
import dev.vinpol.spacetraders.sdk.models.ShipCargo;
import java.io.IOException;

/**
 * SupplyConstruction201ResponseData
 */

public class SupplyConstruction201ResponseData {
  public static final String SERIALIZED_NAME_CONSTRUCTION = "construction";
  
  private Construction construction;

  public static final String SERIALIZED_NAME_CARGO = "cargo";
  
  private ShipCargo cargo;

  public SupplyConstruction201ResponseData() {
  }

  public SupplyConstruction201ResponseData construction(Construction construction) {
    
    this.construction = construction;
    return this;
  }

   /**
   * Get construction
   * @return construction
  **/
  

  public Construction getConstruction() {
    return construction;
  }


  public void setConstruction(Construction construction) {
    this.construction = construction;
  }


  public SupplyConstruction201ResponseData cargo(ShipCargo cargo) {
    
    this.cargo = cargo;
    return this;
  }

   /**
   * Get cargo
   * @return cargo
  **/
  

  public ShipCargo getCargo() {
    return cargo;
  }


  public void setCargo(ShipCargo cargo) {
    this.cargo = cargo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupplyConstruction201ResponseData supplyConstruction201ResponseData = (SupplyConstruction201ResponseData) o;
    return Objects.equals(this.construction, supplyConstruction201ResponseData.construction) &&
        Objects.equals(this.cargo, supplyConstruction201ResponseData.cargo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(construction, cargo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupplyConstruction201ResponseData {\n");
    sb.append("    construction: ").append(toIndentedString(construction)).append("\n");
    sb.append("    cargo: ").append(toIndentedString(cargo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

