/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.vinpol.spacetraders.sdk.models;

import java.util.Objects;
import java.util.Arrays;


import dev.vinpol.spacetraders.sdk.models.Chart;
import dev.vinpol.spacetraders.sdk.models.WaypointFaction;
import dev.vinpol.spacetraders.sdk.models.WaypointModifier;
import dev.vinpol.spacetraders.sdk.models.WaypointOrbital;
import dev.vinpol.spacetraders.sdk.models.WaypointTrait;
import dev.vinpol.spacetraders.sdk.models.WaypointType;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
 */

public class Waypoint {
  public static final String SERIALIZED_NAME_SYMBOL = "symbol";

  private String symbol;

  public static final String SERIALIZED_NAME_TYPE = "type";
  
  private WaypointType type;

  public static final String SERIALIZED_NAME_SYSTEM_SYMBOL = "systemSymbol";
  
  private String systemSymbol;

  public static final String SERIALIZED_NAME_X = "x";
  
  private Integer x;

  public static final String SERIALIZED_NAME_Y = "y";
  
  private Integer y;

  public static final String SERIALIZED_NAME_ORBITALS = "orbitals";
  
  private List<WaypointOrbital> orbitals = new ArrayList<>();

  public static final String SERIALIZED_NAME_ORBITS = "orbits";
  
  private String orbits;

  public static final String SERIALIZED_NAME_FACTION = "faction";
  
  private WaypointFaction faction;

  public static final String SERIALIZED_NAME_TRAITS = "traits";
  
  private List<WaypointTrait> traits = new ArrayList<>();

  public static final String SERIALIZED_NAME_MODIFIERS = "modifiers";
  
  private List<WaypointModifier> modifiers;

  public static final String SERIALIZED_NAME_CHART = "chart";
  
  private Chart chart;

  public static final String SERIALIZED_NAME_IS_UNDER_CONSTRUCTION = "isUnderConstruction";
  
  private Boolean isUnderConstruction;

  public Waypoint() {
  }

  public Waypoint symbol(String symbol) {

    this.symbol = symbol;
    return this;
  }

   /**
   * The symbol of the waypoint.
   * @return symbol
  **/
  

  public String getSymbol() {
    return symbol;
  }


  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public Waypoint type(WaypointType type) {

    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  

  public WaypointType getType() {
    return type;
  }


  public void setType(WaypointType type) {
    this.type = type;
  }


  public Waypoint systemSymbol(String systemSymbol) {

    this.systemSymbol = systemSymbol;
    return this;
  }

   /**
   * The symbol of the system.
   * @return systemSymbol
  **/
  

  public String getSystemSymbol() {
    return systemSymbol;
  }


  public void setSystemSymbol(String systemSymbol) {
    this.systemSymbol = systemSymbol;
  }


  public Waypoint x(Integer x) {

    this.x = x;
    return this;
  }

   /**
   * Relative position of the waypoint on the system&#39;s x axis. This is not an absolute position in the universe.
   * @return x
  **/
  

  public Integer getX() {
    return x;
  }


  public void setX(Integer x) {
    this.x = x;
  }


  public Waypoint y(Integer y) {

    this.y = y;
    return this;
  }

   /**
   * Relative position of the waypoint on the system&#39;s y axis. This is not an absolute position in the universe.
   * @return y
  **/
  

  public Integer getY() {
    return y;
  }


  public void setY(Integer y) {
    this.y = y;
  }


  public Waypoint orbitals(List<WaypointOrbital> orbitals) {

    this.orbitals = orbitals;
    return this;
  }

  public Waypoint addOrbitalsItem(WaypointOrbital orbitalsItem) {
    if (this.orbitals == null) {
      this.orbitals = new ArrayList<>();
    }
    this.orbitals.add(orbitalsItem);
    return this;
  }

   /**
   * Waypoints that orbit this waypoint.
   * @return orbitals
  **/
  

  public List<WaypointOrbital> getOrbitals() {
    return orbitals;
  }


  public void setOrbitals(List<WaypointOrbital> orbitals) {
    this.orbitals = orbitals;
  }


  public Waypoint orbits(String orbits) {

    this.orbits = orbits;
    return this;
  }

   /**
   * The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.
   * @return orbits
  **/
  

  public String getOrbits() {
    return orbits;
  }


  public void setOrbits(String orbits) {
    this.orbits = orbits;
  }


  public Waypoint faction(WaypointFaction faction) {

    this.faction = faction;
    return this;
  }

   /**
   * Get faction
   * @return faction
  **/
  

  public WaypointFaction getFaction() {
    return faction;
  }


  public void setFaction(WaypointFaction faction) {
    this.faction = faction;
  }


  public Waypoint traits(List<WaypointTrait> traits) {

    this.traits = traits;
    return this;
  }

  public Waypoint addTraitsItem(WaypointTrait traitsItem) {
    if (this.traits == null) {
      this.traits = new ArrayList<>();
    }
    this.traits.add(traitsItem);
    return this;
  }

   /**
   * The traits of the waypoint.
   * @return traits
  **/
  

  public List<WaypointTrait> getTraits() {
    return traits;
  }


  public void setTraits(List<WaypointTrait> traits) {
    this.traits = traits;
  }


  public Waypoint modifiers(List<WaypointModifier> modifiers) {

    this.modifiers = modifiers;
    return this;
  }

  public Waypoint addModifiersItem(WaypointModifier modifiersItem) {
    if (this.modifiers == null) {
      this.modifiers = new ArrayList<>();
    }
    this.modifiers.add(modifiersItem);
    return this;
  }

   /**
   * The modifiers of the waypoint.
   * @return modifiers
  **/
  

  public List<WaypointModifier> getModifiers() {
    return modifiers;
  }


  public void setModifiers(List<WaypointModifier> modifiers) {
    this.modifiers = modifiers;
  }


  public Waypoint chart(Chart chart) {

    this.chart = chart;
    return this;
  }

   /**
   * Get chart
   * @return chart
  **/
  

  public Chart getChart() {
    return chart;
  }


  public void setChart(Chart chart) {
    this.chart = chart;
  }


  public Waypoint isUnderConstruction(Boolean isUnderConstruction) {

    this.isUnderConstruction = isUnderConstruction;
    return this;
  }

   /**
   * True if the waypoint is under construction.
   * @return isUnderConstruction
  **/
  

  public Boolean getIsUnderConstruction() {
    return isUnderConstruction;
  }


  public void setIsUnderConstruction(Boolean isUnderConstruction) {
    this.isUnderConstruction = isUnderConstruction;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Waypoint waypoint = (Waypoint) o;
    return Objects.equals(this.symbol, waypoint.symbol) &&
        Objects.equals(this.type, waypoint.type) &&
        Objects.equals(this.systemSymbol, waypoint.systemSymbol) &&
        Objects.equals(this.x, waypoint.x) &&
        Objects.equals(this.y, waypoint.y) &&
        Objects.equals(this.orbitals, waypoint.orbitals) &&
        Objects.equals(this.orbits, waypoint.orbits) &&
        Objects.equals(this.faction, waypoint.faction) &&
        Objects.equals(this.traits, waypoint.traits) &&
        Objects.equals(this.modifiers, waypoint.modifiers) &&
        Objects.equals(this.chart, waypoint.chart) &&
        Objects.equals(this.isUnderConstruction, waypoint.isUnderConstruction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, type, systemSymbol, x, y, orbitals, orbits, faction, traits, modifiers, chart, isUnderConstruction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Waypoint {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    systemSymbol: ").append(toIndentedString(systemSymbol)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    orbitals: ").append(toIndentedString(orbitals)).append("\n");
    sb.append("    orbits: ").append(toIndentedString(orbits)).append("\n");
    sb.append("    faction: ").append(toIndentedString(faction)).append("\n");
    sb.append("    traits: ").append(toIndentedString(traits)).append("\n");
    sb.append("    modifiers: ").append(toIndentedString(modifiers)).append("\n");
    sb.append("    chart: ").append(toIndentedString(chart)).append("\n");
    sb.append("    isUnderConstruction: ").append(toIndentedString(isUnderConstruction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

