<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar-content">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbar-content" class="navbar-menu">
        <div class="navbar-start">
            <a href="https://docs.spacetraders.io/" class="navbar-item">📄 Docs</a>
        </div>

        <div class="navbar-center">
            <a href="/" class="navbar-item">🏠 Home</a>
            <a href="/fleet" class="navbar-item">🚀 Fleet</a>
            <a href="/galaxy" class="navbar-item">🌌 Galaxy</a>
            <a href="/contracts" class="navbar-item">📦 Contracts</a>
        </div>

        <div class="navbar-end">
            <a href="/settings" class="navbar-item">⚙️ Settings</a>
        </div>
    </div>
</nav>
